"""modify models

Revision ID: 767019deff9d
Revises: 14b481f05ffc
Create Date: 2025-05-09 16:21:32.018421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '767019deff9d'
down_revision: Union[str, None] = '14b481f05ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leave_request_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['leave_request_id'], ['leave_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('leave_request_attachments')
    op.add_column('departments', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('departments', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('departments', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('departments_name_key', 'departments', type_='unique')
    op.alter_column('leave_requests', 'request_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('leave_requests', 'proxy_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('leave_requests', 'start_half_day',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('leave_requests', 'end_half_day',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('leave_requests', 'days_count',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=5, scale=1),
               nullable=False)
    op.alter_column('leave_requests', 'reason',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('leave_requests', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='leavestatus'),
               nullable=False)
    op.alter_column('leave_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('leave_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('leave_types', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('leave_types', sa.Column('requires_attachment', sa.Boolean(), server_default='False', nullable=True))
    op.add_column('leave_types', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('leave_types', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('leave_types', 'color_code',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=20),
               nullable=False)
    op.drop_constraint('leave_types_name_key', 'leave_types', type_='unique')
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('notifications', 'related_to',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('notifications', 'related_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('users', sa.Column('annual_leave_quota', sa.Integer(), server_default='7', nullable=False))
    op.add_column('users', sa.Column('sick_leave_quota', sa.Integer(), server_default='30', nullable=False))
    op.add_column('users', sa.Column('personal_leave_quota', sa.Integer(), server_default='14', nullable=False))
    op.add_column('users', sa.Column('public_holiday_quota', sa.Integer(), server_default='5', nullable=False))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'position',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'hire_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('users', 'is_manager',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_manager',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'hire_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'position',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.alter_column('users', 'employee_id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'public_holiday_quota')
    op.drop_column('users', 'personal_leave_quota')
    op.drop_column('users', 'sick_leave_quota')
    op.drop_column('users', 'annual_leave_quota')
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('notifications', 'related_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('notifications', 'related_to',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('notifications', 'title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=True)
    op.create_unique_constraint('leave_types_name_key', 'leave_types', ['name'])
    op.alter_column('leave_types', 'color_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=7),
               nullable=True)
    op.drop_column('leave_types', 'updated_at')
    op.drop_column('leave_types', 'created_at')
    op.drop_column('leave_types', 'requires_attachment')
    op.drop_column('leave_types', 'description')
    op.alter_column('leave_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('leave_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('leave_requests', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='leavestatus'),
               nullable=True)
    op.alter_column('leave_requests', 'reason',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('leave_requests', 'days_count',
               existing_type=sa.DECIMAL(precision=5, scale=1),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('leave_requests', 'end_half_day',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('leave_requests', 'start_half_day',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('leave_requests', 'proxy_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('leave_requests', 'request_id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_unique_constraint('departments_name_key', 'departments', ['name'])
    op.drop_column('departments', 'updated_at')
    op.drop_column('departments', 'created_at')
    op.drop_column('departments', 'description')
    op.create_table('leave_request_attachments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('leave_request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['leave_request_id'], ['leave_requests.id'], name='leave_request_attachments_leave_request_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='leave_request_attachments_pkey')
    )
    op.drop_table('leave_attachments')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
