"""fix relationship

Revision ID: 774074b0e8a8
Revises: 767019deff9d
Create Date: 2025-05-10 19:58:15.522083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '774074b0e8a8'
down_revision: Union[str, None] = '767019deff9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'annual_leave_quota')
    op.drop_column('users', 'personal_leave_quota')
    op.drop_column('users', 'sick_leave_quota')
    op.drop_column('users', 'public_holiday_quota')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_holiday_quota', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('sick_leave_quota', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('personal_leave_quota', sa.INTEGER(), server_default=sa.text('14'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('annual_leave_quota', sa.INTEGER(), server_default=sa.text('7'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
