"""fix relationship

Revision ID: bbe2b8f6a080
Revises: 774074b0e8a8
Create Date: 2025-05-10 21:57:12.093921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe2b8f6a080'
down_revision: Union[str, None] = '774074b0e8a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_department_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_department_id_fkey', 'users', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###
