"""fix request model

Revision ID: c3bdb8e2e434
Revises: 5e408b4b24b9
Create Date: 2025-05-11 16:45:48.462646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3bdb8e2e434'
down_revision: Union[str, None] = '5e408b4b24b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_requests', 'start_half_day')
    op.drop_column('leave_requests', 'end_half_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('end_half_day', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('leave_requests', sa.Column('start_half_day', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
