"""change leave status type

Revision ID: db94663432fd
Revises: c3bdb8e2e434
Create Date: 2025-05-11 17:11:10.224789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db94663432fd'
down_revision: Union[str, None] = 'c3bdb8e2e434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('start_half_day', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('leave_requests', sa.Column('end_half_day', sa.Boolean(), server_default='False', nullable=False))
    op.alter_column('leave_requests', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='leavestatus'),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leave_requests', 'status',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('pending', 'approved', 'rejected', name='leavestatus'),
               existing_nullable=False)
    op.drop_column('leave_requests', 'end_half_day')
    op.drop_column('leave_requests', 'start_half_day')
    # ### end Alembic commands ###
